# Unity build: every mylibs/*.c is amalgamated into mylib.h - no per-lib
# headers. For each .c file:
#   - top matter (includes/defines/types before the first function) and
#     auto-extracted prototypes of its non-static functions go into the
#     declaration section, visible to every includer
#   - the function definitions go behind MYLIB_IMPLEMENTATION (defined in
#     exactly one .c file: src/main.c)
# Conventions (raylib style per .clang-format): one-line function signatures
# with the opening brace on its own line; file-scope state should be static.
#
# Run standalone with: cmake -P mylibs/amalgamate.cmake

set(MYLIBS_DIR "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB SOURCES "${MYLIBS_DIR}/*.c")
list(SORT SOURCES)

set(DECLS "")
set(IMPLS "")

foreach(source ${SOURCES})
    get_filename_component(name "${source}" NAME)
    file(READ "${source}" contents)
    string(REGEX REPLACE "[ \t]*#[ \t]*include[ \t]+\"[^\"]*\"[^\n]*\n" "" contents "${contents}")

    # First top-level function definition marks the start of the implementation part
    string(REGEX MATCH "\n[A-Za-z_][^\n;{}]*\\([^)]*\\)[ \t\r]*\n\\{" first_func "${contents}")
    if(first_func)
        string(FIND "${contents}" "${first_func}" split_at)
        string(SUBSTRING "${contents}" 0 ${split_at} top)
        string(SUBSTRING "${contents}" ${split_at} -1 impl)
    else()
        set(top "${contents}")
        set(impl "")
    endif()

    # Auto-generate prototypes for the non-static functions
    set(protos "")
    string(REGEX MATCHALL "\n[A-Za-z_][^\n;{}]*\\([^)]*\\)[ \t\r]*\n\\{" funcs "${impl}")
    foreach(func ${funcs})
        string(REGEX REPLACE "^\n" "" sig "${func}")
        string(REGEX REPLACE "[ \t\r]*\n\\{$" "" sig "${sig}")
        if(NOT sig MATCHES "^static[ \t]")
            string(APPEND protos "${sig};\n")
        endif()
    endforeach()

    string(APPEND DECLS "\n// ---- ${name} (declarations) ----\n${top}${protos}")
    string(APPEND IMPLS "\n// ---- ${name} ----${impl}\n")
endforeach()

set(OUT "")
string(APPEND OUT "// GENERATED by mylibs/amalgamate.cmake - do not edit by hand\n")
string(APPEND OUT "// Unity build of mylibs/*.c; MYLIB_IMPLEMENTATION is defined in src/main.c\n")
string(APPEND OUT "#ifndef MYLIB_H\n#define MYLIB_H\n")
string(APPEND OUT "${DECLS}")
string(APPEND OUT "\n#endif // MYLIB_H\n")
string(APPEND OUT "\n#ifdef MYLIB_IMPLEMENTATION\n#ifndef MYLIB_IMPLEMENTATION_DONE\n#define MYLIB_IMPLEMENTATION_DONE\n")
string(APPEND OUT "${IMPLS}")
string(APPEND OUT "\n#endif // MYLIB_IMPLEMENTATION_DONE\n#endif // MYLIB_IMPLEMENTATION\n")

file(WRITE "${MYLIBS_DIR}/mylib.h" "${OUT}")
message(STATUS "mylibs: generated ${MYLIBS_DIR}/mylib.h")
