# Amalgamates every .h/.c in this directory into mylib.h (stb-style):
# all headers first, then implementations behind MYLIB_IMPLEMENTATION.
# Local #include "..." lines are stripped (everything is already inlined);
# system #include <...> lines are kept.
#
# Run standalone with: cmake -P mylibs/amalgamate.cmake

set(MYLIBS_DIR "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB HEADERS "${MYLIBS_DIR}/*.h")
file(GLOB SOURCES "${MYLIBS_DIR}/*.c")
list(REMOVE_ITEM HEADERS "${MYLIBS_DIR}/mylib.h")
list(SORT HEADERS)
list(SORT SOURCES)

set(OUT "")
string(APPEND OUT "// GENERATED by mylibs/amalgamate.cmake - do not edit by hand\n")
string(APPEND OUT "// Define MYLIB_IMPLEMENTATION in exactly one .c file before including\n")
string(APPEND OUT "#ifndef MYLIB_H\n#define MYLIB_H\n")

foreach(header ${HEADERS})
    get_filename_component(name "${header}" NAME)
    file(READ "${header}" contents)
    string(REGEX REPLACE "[ \t]*#[ \t]*include[ \t]+\"[^\"]*\"[^\n]*\n" "" contents "${contents}")
    string(APPEND OUT "\n// ---- ${name} ----\n${contents}")
endforeach()

string(APPEND OUT "\n#endif // MYLIB_H\n")
string(APPEND OUT "\n#ifdef MYLIB_IMPLEMENTATION\n#ifndef MYLIB_IMPLEMENTATION_DONE\n#define MYLIB_IMPLEMENTATION_DONE\n")

foreach(source ${SOURCES})
    get_filename_component(name "${source}" NAME)
    file(READ "${source}" contents)
    string(REGEX REPLACE "[ \t]*#[ \t]*include[ \t]+\"[^\"]*\"[^\n]*\n" "" contents "${contents}")
    string(APPEND OUT "\n// ---- ${name} ----\n${contents}")
endforeach()

string(APPEND OUT "\n#endif // MYLIB_IMPLEMENTATION_DONE\n#endif // MYLIB_IMPLEMENTATION\n")

file(WRITE "${MYLIBS_DIR}/mylib.h" "${OUT}")
message(STATUS "mylibs: generated ${MYLIBS_DIR}/mylib.h")
