// GENERATED by mylibs/amalgamate.cmake - do not edit by hand
// Unity build of mylibs/*.c; MYLIB_IMPLEMENTATION is defined in src/main.c
#ifndef MYLIB_H
#define MYLIB_H

// ---- mymath.c (declarations) ----
/*******************************************************************************************
*
*   mymath - starter example lib for the mylibs unity build
*
*   Just a .c file, no header needed: amalgamate.cmake hoists everything above
*   the first function (includes, defines, types) plus auto-generated prototypes
*   into mylib.h's declaration section; function bodies go behind MYLIB_IMPLEMENTATION
*
********************************************************************************************/
int MyClampInt(int value, int min, int max);
float MyLerpF(float start, float end, float amount);

#endif // MYLIB_H

#ifdef MYLIB_IMPLEMENTATION
#ifndef MYLIB_IMPLEMENTATION_DONE
#define MYLIB_IMPLEMENTATION_DONE

// ---- mymath.c ----
int MyClampInt(int value, int min, int max)
{
    if (value < min) return min;
    if (value > max) return max;
    return value;
}

float MyLerpF(float start, float end, float amount)
{
    return start + amount*(end - start);
}


#endif // MYLIB_IMPLEMENTATION_DONE
#endif // MYLIB_IMPLEMENTATION
