// GENERATED by mylibs/amalgamate.cmake - do not edit by hand
// Define MYLIB_IMPLEMENTATION in exactly one .c file before including
#ifndef MYLIB_H
#define MYLIB_H

// ---- mymath.h ----
/*******************************************************************************************
*
*   mymath - starter example lib for the mylibs unity build
*
*   Drop .h/.c pairs into mylibs/ and they get amalgamated into mylib.h
*
********************************************************************************************/

#ifndef MYMATH_H
#define MYMATH_H

int MyClampInt(int value, int min, int max);
float MyLerpF(float start, float end, float amount);

#endif // MYMATH_H

#endif // MYLIB_H

#ifdef MYLIB_IMPLEMENTATION
#ifndef MYLIB_IMPLEMENTATION_DONE
#define MYLIB_IMPLEMENTATION_DONE

// ---- mymath.c ----

int MyClampInt(int value, int min, int max)
{
    if (value < min) return min;
    if (value > max) return max;
    return value;
}

float MyLerpF(float start, float end, float amount)
{
    return start + amount*(end - start);
}

#endif // MYLIB_IMPLEMENTATION_DONE
#endif // MYLIB_IMPLEMENTATION
